// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded to ensure the app always connects to the correct Supabase project,
// regardless of hosting platform env vars. The anon key is public by design.
const SUPABASE_URL = "https://jlytabfuiwfacfbowiyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpseXRhYmZ1aXdmYWNmYm93aXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NzE5MzcsImV4cCI6MjA4OTQ0NzkzN30.uc8Ipb5XMKLzKiA1IGG60qJasklMOHPe_03BflxtAY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Use implicit flow for OAuth — tokens come directly in the URL hash,
    // no PKCE code exchange needed. More reliable for SPAs.
    flowType: 'implicit',
    // Detect OAuth tokens in the URL hash on page load
    detectSessionInUrl: true,
    // Bypass navigator.locks entirely to avoid deadlocks caused by stale locks
    // after page reloads or tab crashes in the preview/iframe environment.
    // This is safe for single-tab usage which is the typical case for this app.
    lock: <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>) => fn(),
  }
});